-- migrate:up
-- Standardize identity generation strategy from BY DEFAULT to ALWAYS
-- This prevents manual ID insertion conflicts and ensures consistency

-- email_templates: Change from BY DEFAULT to ALWAYS
ALTER TABLE public.email_templates 
    ALTER COLUMN id DROP IDENTITY;

ALTER TABLE public.email_templates 
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- ticket_history: Change from BY DEFAULT to ALWAYS
ALTER TABLE public.ticket_history 
    ALTER COLUMN id DROP IDENTITY;

ALTER TABLE public.ticket_history 
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- migrate:down
-- Revert to GENERATED BY DEFAULT for rollback

ALTER TABLE public.email_templates 
    ALTER COLUMN id DROP IDENTITY;

ALTER TABLE public.email_templates 
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.ticket_history 
    ALTER COLUMN id DROP IDENTITY;

ALTER TABLE public.ticket_history 
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
