CREATE TABLE "user_email_changes" (
	"user_id" integer NOT NULL,
	"old" varchar(254) NOT NULL,
	"new" varchar(254) NOT NULL,
	"confirm_token" varchar(100) NOT NULL,
	"undo_token" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer NOT NULL,
	"confirmed_at" timestamp with time zone,
	"confirm_max_age" integer NOT NULL,
	"undo_max_age" integer NOT NULL,
	"undone_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "email_templates" DROP CONSTRAINT "email_templates_workspace_id_template_type_id_unique";--> statement-breakpoint
ALTER TABLE "email_templates" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "user_email_changes" ADD CONSTRAINT "user_email_changes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_email_changes" ADD CONSTRAINT "user_email_changes_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "email_templates" ADD CONSTRAINT "email_templates_workspace_id_template_type_id_unique" UNIQUE NULLS NOT DISTINCT("workspace_id","template_type_id");