ALTER TABLE "email_templates" DROP CONSTRAINT "email_templates_workspace_id_template_type_id_unique";--> statement-breakpoint
ALTER TABLE "email_templates" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "user_email_changes" ADD COLUMN "undone_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "email_templates" ADD CONSTRAINT "email_templates_workspace_id_template_type_id_unique" UNIQUE NULLS NOT DISTINCT("workspace_id","template_type_id");